grass:
  # === dataloader ===
  split_ratio: 0.8
  batch_size: 16
  num_classes: 12
  
  # === training setting ===
  learning_rate: 0.001
  weight_decay: 0.001
  num_epochs: 100
  early_stop_counts: 10
  patience: 3
  factor: 0.5
  min_lr: 0.0001